In [44]:
import numpy as np
import pandas

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

from sklearn.decomposition import PCA

In [2]:
d = pandas.read_csv('Breast_cancer_data.csv')

In [3]:
d.shape

(569, 6)

In [4]:
d.head(25)

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.990         10.38          122.80     1001.0          0.11840   
1        20.570         17.77          132.90     1326.0          0.08474   
2        19.690         21.25          130.00     1203.0          0.10960   
3        11.420         20.38           77.58      386.1          0.14250   
4        20.290         14.34          135.10     1297.0          0.10030   
5        12.450         15.70           82.57      477.1          0.12780   
6        18.250         19.98          119.60     1040.0          0.09463   
7        13.710         20.83           90.20      577.9          0.11890   
8        13.000         21.82           87.50      519.8          0.12730   
9        12.460         24.04           83.97      475.9          0.11860   
10       16.020         23.24          102.70      797.8          0.08206   
11       15.780         17.89          103.60      781.0          0.09710   
12       19.170         24.80          132.40     1123.0          0.09740   
13       15.850         23.95          103.70      782.7          0.08401   
14       13.730         22.61           93.60      578.3          0.11310   
15       14.540         27.54           96.73      658.8          0.11390   
16       14.680         20.13           94.74      684.5          0.09867   
17       16.130         20.68          108.10      798.8          0.11700   
18       19.810         22.15          130.00     1260.0          0.09831   
19       13.540         14.36           87.46      566.3          0.09779   
20       13.080         15.71           85.63      520.0          0.10750   
21        9.504         12.44           60.34      273.9          0.10240   
22       15.340         14.26          102.50      704.4          0.10730   
23       21.160         23.04          137.20     1404.0          0.09428   
24       16.650         21.38          110.00      904.6          0.11210   

    diagnosis  
0           0  
1           0  
2           0  
3           0  
4           0  
5           0  
6           0  
7           0  
8           0  
9           0  
10          0  
11          0  
12          0  
13          0  
14          0  
15          0  
16          0  
17          0  
18          0  
19          1  
20          1  
21          1  
22          0  
23          0  
24          0

In [14]:
xp = d.iloc[:,0:4]
yp = d.iloc[:,5]

In [15]:
yp.shape

(569,)

In [16]:
xp.iloc[0,:]

mean_radius         17.99
mean_texture        10.38
mean_perimeter     122.80
mean_area         1001.00
Name: 0, dtype: float64

In [18]:
#let's go to numpy
X = xp.to_numpy()
Y = yp.to_numpy()

In [22]:
#test_train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [27]:
Y_pred = GaussianNB().fit(X_train, Y_train).predict(X_test)

In [28]:
Y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1])

In [29]:
Y_test

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1])

In [30]:
#as we can see the predicted target is somewhat similar to the real target
#but we must speak in the measures language

In [42]:
print("Number of dismatches from %d points is: %d"% (X_test.shape[0], (Y_test != Y_pred).sum()))

Number of dismatches from 114 points is: 10


In [36]:
confusion_matrix(Y_test, Y_pred)

array([[41,  6],
       [ 4, 63]])

In [78]:
f1_score(Y_test, Y_pred, average='binary')

0.9264705882352942

In [43]:
#which means we were a success!

In [71]:
#X_r means X dimention reduced
X_r = PCA(n_components=3).fit_transform(X)

In [72]:
X

array([[  17.99,   10.38,  122.8 , 1001.  ],
       [  20.57,   17.77,  132.9 , 1326.  ],
       [  19.69,   21.25,  130.  , 1203.  ],
       ...,
       [  16.6 ,   28.08,  108.3 ,  858.1 ],
       [  20.6 ,   29.33,  140.1 , 1265.  ],
       [   7.76,   24.54,   47.92,  181.  ]])

In [73]:
X_r

array([[ 3.47389677e+02,  3.45350626e+00, -1.20746947e+01],
       [ 6.72360685e+02,  6.22361694e+00,  1.09934282e+00],
       [ 5.49459884e+02, -2.91295525e-01, -6.66575231e-01],
       ...,
       [ 2.03898289e+02, -7.80257581e+00,  3.05462131e+00],
       [ 6.12040081e+02, -1.00651255e+01, -3.02356656e-01],
       [-4.75802608e+02,  1.90417629e+00,  1.36947109e+01]])

In [74]:
#test_train
X_r_train, X_r_test, Y_r_train, Y_r_test = train_test_split(X_r, Y, test_size=0.2, random_state=0)

In [79]:
Y_r_pred = GaussianNB().fit(X_r_train, Y_r_train).predict(X_r_test)

In [80]:
print("Number of dismatches from %d points is: %d"% (X_r_test.shape[0], (Y_r_test != Y_r_pred).sum()))

Number of dismatches from 114 points is: 9


In [81]:
confusion_matrix(Y_r_test, Y_r_pred)

array([[41,  6],
       [ 3, 64]])

In [82]:
f1_score(Y_r_test, Y_r_pred, average='binary')

0.9343065693430657

In [84]:
#X_r means X dimention reduced
X_r_2 = PCA(n_components=2).fit_transform(X)

In [85]:
#test_train
X_r_2_train, X_r_2_test, Y_r_2_train, Y_r_2_test = train_test_split(X_r_2, Y, test_size=0.2, random_state=0)

In [86]:
Y_r_2_pred = GaussianNB().fit(X_r_2_train, Y_r_2_train).predict(X_r_2_test)

In [87]:
print("Number of dismatches from %d points is: %d"% (X_r_2_test.shape[0], (Y_r_2_test != Y_r_2_pred).sum()))

Number of dismatches from 114 points is: 11


In [88]:
confusion_matrix(Y_r_2_test, Y_r_2_pred)

array([[40,  7],
       [ 4, 63]])

In [89]:
f1_score(Y_r_2_test, Y_r_2_pred, average='binary')

0.9197080291970803

In [92]:
D = d.to_numpy()

In [93]:
D

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 0.000e+00],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 0.000e+00],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 0.000e+00],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, 8.581e+02, 8.455e-02, 0.000e+00],
       [2.060e+01, 2.933e+01, 1.401e+02, 1.265e+03, 1.178e-01, 0.000e+00],
       [7.760e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02, 1.000e+00]])

In [101]:
#mean and variance
D_yes = np.empty([6])
for i in D:
    if i[5] == 0.0:
        np.append(i,D_yes)
        

In [102]:
D_yes

array([7.760e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02, 1.000e+00])